codecov:
  max_report_age: off  # Disable the 12h age check for reports
  notify:
    after_n_builds: 1  # Wait for 1 build to complete before processing

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false