version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: aevatar-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/admin -u admin -p admin --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: always

volumes:
  mongodb_data: 