<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="..\..\common.props" />
    <PropertyGroup>
        <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
        <Nullable>enable</Nullable>
        <RootNamespace>AISmart</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Aevatar.GAgents.Basic\Aevatar.GAgents.Basic.csproj" />
        <ProjectReference Include="..\Aevatar.GAgents.AI.Abstractions\Aevatar.GAgents.AI.Abstractions.csproj" />
        <ProjectReference Include="..\..\..\framework\src\Aevatar.Core\Aevatar.Core.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="AElf.Sdk.CSharp" />
        <PackageReference Include="Microsoft.Orleans.EventSourcing" />
        <PackageReference Include="Volo.Abp.AutoMapper" />
    </ItemGroup>
</Project>