receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4315
      http:

processors:
  batch:
  memory_limiter:
    check_interval: 1s
    limit_mib: 1000
    spike_limit_mib: 200
  spanmetrics:
    metrics_exporter: prometheus
    aggregation_temporality: CUMULATIVE

exporters:
  otlp:
    endpoint: "jaeger:4317"
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:9090"
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, memory_limiter, spanmetrics]
      exporters: [otlp, debug]
    metrics:
      receivers: [otlp]
      processors: [batch, memory_limiter]
      exporters: [prometheus, debug] 