<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
        <PackageReference Include="Swashbuckle.AspNetCore" />
        <PackageReference Include="Newtonsoft.Json" />
        <PackageReference Include="Microsoft.Extensions.Hosting" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\src\Aevatar.GAgents.MCP\Aevatar.GAgents.MCP.csproj" />
        <ProjectReference Include="..\..\..\src\Aevatar.GAgents.MCP.Core\Aevatar.GAgents.MCP.Core.csproj" />
        <ProjectReference Include="..\..\..\test\Aevatar.GAgents.TestBase\Aevatar.GAgents.TestBase.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Update="wwwroot\**\*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
      <Content Update="appsettings.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

</Project>
