<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Aevatar.GAgents.Basic</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Volo.Abp.AutoMapper" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../../framework/src/Aevatar.Core/Aevatar.Core.csproj" />
    <ProjectReference Include="../../../framework/src/Aevatar.Core.Abstractions/Aevatar.Core.Abstractions.csproj" />
  </ItemGroup>
</Project>