global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'opentelemetry-collector'
    static_configs:
      - targets: ['otel-collector:9090']
    
  - job_name: 'aevatar-services'
    static_configs:
      - targets: ['host.docker.internal:9090']
    
  # Add a Prometheus self-monitoring job
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
