<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
        <Nullable>enable</Nullable>
        <RootNamespace>Aevatar.GAgents.Speech</RootNamespace>
        <NoWarn>$(NoWarn);SKEXP0001;SKEXP0010;SKEXP0020;SKEXP0070</NoWarn>
        <PackageId>Aevatar.GAgents.Speech</PackageId>
        <PackageType>Dependency</PackageType>
        <Title>aevatar GAgents</Title>
        <Authors>AElf</Authors>
        <PackageTags>agent</PackageTags>
        <RepositoryUrl>https://github.com/aevatarAI/aevatar-gagents</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageProjectUrl>https://github.com/aevatarAI/aevatar-gagents</PackageProjectUrl>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CognitiveServices.Speech" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Aevatar.GAgents.Basic\Aevatar.GAgents.Basic.csproj" />
    </ItemGroup>

</Project>
