<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="Fody" />
        <PackageReference Include="MethodDecorator.Fody" />
    </ItemGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\..\..\framework\src\Aevatar.Core.Abstractions\Aevatar.Core.Abstractions.csproj" />
        <ProjectReference Include="..\..\..\framework\src\Aevatar.Core\Aevatar.Core.csproj" />
        <ProjectReference Include="..\..\..\framework\src\Aevatar.EventSourcing.Core\Aevatar.EventSourcing.Core.csproj" />
        <ProjectReference Include="..\..\..\framework\src\Aevatar.Core.Interception\Aevatar.Core.Interception.csproj" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\Aevatar.GAgents.GroupChat.GroupMember\Aevatar.GAgents.GroupChat.GroupMember.csproj" />
        <ProjectReference Include="..\Aevatar.GAgents.Core\Aevatar.GAgents.Core.csproj" />
        <ProjectReference Include="..\Aevatar.GAgents.Workflow\Aevatar.GAgents.Workflow.csproj" />
    </ItemGroup>
</Project>