receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
    send_batch_size: 1000
    timeout: 10s
  memory_limiter:
    check_interval: 1s
    limit_mib: 1000
    spike_limit_mib: 200
    verbosity: detailed
  prometheus:
    endpoint: "0.0.0.0:9090"
  elasticsearch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, memory_limiter]
