name: Test Production Environment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Echo deployment message
        run: echo "Deploying to production environment!"
