name: Publish MyGet Package

on:
  push:
    tags:
      - "v*.*.*"

run-name: Publish MyGet Package from ${{ github.ref }}

env:
  DOTNET_INSTALL_DIR: "./.dotnet"

concurrency:
  group: workflow-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Aevatar
            path: src/Aevatar
            project_root: framework
          - name: Aevatar.Core
            path: src/Aevatar.Core
            project_root: framework
          - name: Aevatar.Core.Abstractions
            path: src/Aevatar.Core.Abstractions
            project_root: framework
          - name: Aevatar.EventSourcing.Core
            path: src/Aevatar.EventSourcing.Core
            project_root: framework
          - name: Aevatar.EventSourcing.MongoDB
            path: src/Aevatar.EventSourcing.MongoDB
            project_root: framework
          - name: Aevatar.PermissionManagement
            path: src/Aevatar.PermissionManagement
            project_root: framework
          - name: Aevatar.Plugins
            path: src/Aevatar.Plugins
            project_root: framework
          - name: Aevatar.SignalR
            path: src/Aevatar.SignalR
            project_root: signalR
          - name: Aevatar.CQRS
            path: src/Aevatar.CQRS
            project_root: station
          - name: Aevatar.WebHook.SDK
            path: src/Aevatar.WebHook.SDK
            project_root: station
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Cache NuGet Packages
        id: nuget-packages
        uses: actions/cache@v4
        env:
          cache-name: nuget-package-cache
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-${{ env.cache-name }}

      - name: Restore dependencies
        run: cd ${{ matrix.project_root }} && dotnet restore ${{ matrix.path }}/${{ matrix.name }}.csproj

      - name: Get the version from git tags
        id: get_version
        run: |
          TAG=$(git describe --tags --abbrev=0)
          VERSION=${TAG#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build the project
        run: cd ${{ matrix.project_root }} && dotnet build ${{ matrix.path }}/${{ matrix.name }}.csproj --configuration Release --no-restore

      - name: Pack the MyGet package
        run: cd ${{ matrix.project_root }} && dotnet pack ${{ matrix.path }}/${{ matrix.name }}.csproj --configuration Release --no-build --output ../../nupkg -p:PackageVersion=${{ env.VERSION }}

      - name: Publish the MyGet package
        env:
          MYGET_URL: ${{ secrets.MYGET_URL }}
          MYGET_API_KEY: ${{ secrets.MYGET_API_KEY }}
        run: dotnet nuget push ./nupkg/*.nupkg --api-key $MYGET_API_KEY --source $MYGET_URL 